#自定义路由 当然可以放在git上面实现动态路由
#zuul:
#  #全部服务忽略敏感头（全部服务都可以用传递cookie）
#  sensitive-headers:
#  routes:
#    #sensitiveHeaders让cookie可以传递过来
#    myProducer:
#      path: /myProducer/**
#      serviceId: producer
#      sensitiveHeaders:
#    #简便写法
##    producer: /myProducer/**
#    #让以下的接口无法被访问,更简单可以写成下面的通配符的方式
#  ignored-patterns:
##    - /producer/list
##    - /myProducer/list
#    - /**/list
#zuul超时配置
#hystrix:
#  command:
#    #全局
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000

