#端口号
server:
  port: 8080
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: producer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://106.12.27.130:3306/map?characterEncoding=utf-8&useSSL=false
eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8888/eureka/
#数据库mapper文件映射地址
mybatis:
  mapper-locations: classpath:/mapping/*.xml