#端口号
server:
  port: 8084
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vivolvle/config_repo_kafka.git
          username: 1067310192@qq.com
          password: 1771291wei
          #把从git上拉取下来的配置文件存放本地的位置
          basedir: /cloud/kafka
    stream:
      kafka:
        binder:
          #Kafka的服务端列表，默认localhost
          brokers: 106.12.27.130:9092
          defaultBrokerPort: 9092
          zkNodes: 106.12.27.130:2181
          defaultZkPort: 2181
  kafka:
    bootstrap-servers: 106.12.27.130:9092
    consumer:
      group-id: test
eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      #以下是部署到云服务器上的域名
      #defaultZone: http://bus.vivolvle.cn:8888/eureka/
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        #不要写成bus-refresh,因为git使用的是monitor
        include: "*"
