#端口号
server:
  port: 8084
#Eureka实例名，集群中根据这里相互识别
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vivolvle/config_repo
          username: 1067310192@qq.com
          password: 1771291wei
          #把从git上拉取下来的配置文件存放本地的位置
          basedir: /cloud/config
  rabbitmq:
    host: 106.12.27.130
    port: 5672
    username: guest
    password: guest
eureka:
  #客户端
  client:
    #注册中心地址
    service-url:
      defaultZone: http://localhost:8888/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
